-- begin POLYCLINIC_RECIPE
alter table POLYCLINIC_RECIPE add constraint FK_POLYCLINIC_RECIPE_ON_DOCTOR foreign key (DOCTOR_ID) references POLYCLINIC_DOCTOR(ID)^
create index IDX_POLYCLINIC_RECIPE_ON_DOCTOR on POLYCLINIC_RECIPE (DOCTOR_ID)^
-- end POLYCLINIC_RECIPE
-- begin POLYCLINIC_RECIPE_PATIENT_LINK
alter table POLYCLINIC_RECIPE_PATIENT_LINK add constraint FK_RECPAT_ON_RECIPE foreign key (RECIPE_ID) references POLYCLINIC_RECIPE(ID)^
alter table POLYCLINIC_RECIPE_PATIENT_LINK add constraint FK_RECPAT_ON_PATIENT foreign key (PATIENT_ID) references POLYCLINIC_PATIENT(ID)^
-- end POLYCLINIC_RECIPE_PATIENT_LINK
