alter table POLYCLINIC_RECIPE add constraint FK_POLYCLINIC_RECIPE_ON_DOCTOR foreign key (DOCTOR_ID) references POLYCLINIC_DOCTOR(ID);
create index IDX_POLYCLINIC_RECIPE_ON_DOCTOR on POLYCLINIC_RECIPE (DOCTOR_ID);
